### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name" : "짭종",
  "email": "ilikeamoney@naver.com",
  "password": "1234"
}


### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "ilikeamoney@naver.com",
  "password": "1234"
}

### 사용자 페이지
GET http://localhost:8080/member

### 관리자 페이지
GET http://localhost:8080/admin

### 메인 페이지
GET http://localhost:8080